name: fair
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py39h06a4308_1
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=2022.10=py39_0
  - anaconda-client=1.11.0=py39h06a4308_0
  - anaconda-navigator=2.3.1=py39h06a4308_0
  - anaconda-project=0.11.1=py39h06a4308_0
  - anyio=3.5.0=py39h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - arrow=1.2.2=pyhd3eb1b0_0
  - astroid=2.11.7=py39h06a4308_0
  - astropy=5.1=py39h7deecbd_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py39h5eee18b_1
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bitarray=2.5.1=py39h5eee18b_0
  - bkcharts=0.2=py39h06a4308_1
  - black=22.6.0=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h4ff587b_1
  - bokeh=2.4.3=py39h06a4308_0
  - boost-cpp=1.70.0=ha2d47e9_1
  - boto3=1.24.28=py39h06a4308_0
  - botocore=1.27.28=py39h06a4308_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cairo=1.16.0=h19f5f5c_2
  - cfitsio=3.470=h5893167_7
  - chardet=4.0.0=py39h06a4308_1003
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py39h06a4308_1
  - colorama=0.4.5=py39h06a4308_0
  - colorcet=3.0.0=py39h06a4308_0
  - conda=22.11.1=py39hf3d152e_1
  - conda-build=3.22.0=py39h06a4308_0
  - conda-content-trust=0.1.3=py39h06a4308_0
  - conda-env=2.6.0=1
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.9.0=py39h5eee18b_0
  - conda-repo-cli=1.0.20=py39h06a4308_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - constantly=15.1.0=pyh2b92418_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - cudatoolkit=11.2.2=hbe64b41_10
  - cudnn=8.1.0.77=h90431f1_0
  - curl=7.84.0=h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.32=py39h6a678d5_0
  - daal4py=2021.6.0=py39h79cecc1_1
  - dal=2021.6.0=hdb19cb5_916
  - dataclasses=0.8=pyh6d0b6a4_7
  - datashader=0.14.1=py39h06a4308_0
  - datashape=0.5.4=py39h06a4308_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - distributed=2022.7.0=py39h06a4308_0
  - docutils=0.18.1=py39h06a4308_3
  - entrypoints=0.4=py39h06a4308_0
  - et_xmlfile=1.1.0=py39h06a4308_0
  - expat=2.4.9=h6a678d5_0
  - fftw=3.3.9=h27cfd23_1
  - filelock=3.6.0=pyhd3eb1b0_0
  - flake8=4.0.1=pyhd3eb1b0_1
  - flask=1.1.2=pyhd3eb1b0_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - freexl=1.0.6=h7f98852_0
  - future=0.18.2=py39h06a4308_1
  - gensim=4.1.2=py39h295c915_0
  - geos=3.8.0=he6710b0_0
  - geotiff=1.7.0=hd69d5b1_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - greenlet=1.1.1=py39h295c915_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.6=h3ffc7dd_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.15.0=py39h06a4308_0
  - hvplot=0.8.0=py39h06a4308_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imagesize=1.4.1=py39h06a4308_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py39h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.5=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.15.2=py39h06a4308_0
  - ipython=7.31.1=py39h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.18.1=py39h06a4308_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=0.9.0=py39h7f8727e_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jq=1.6=h27cfd23_1000
  - json-c=0.13.1=hbfbb72e_1002
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.16.0=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_8
  - jupyter_client=7.3.4=py39h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.11.1=py39h06a4308_0
  - jupyter_server=1.18.1=py39h06a4308_0
  - jupyterlab=3.4.4=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - kealib=1.4.14=hb50703a_1
  - keyring=23.4.0=py39h06a4308_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.2=hac12032_0
  - lazy-object-proxy=1.6.0=py39h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libarchive=3.6.1=hab531cd_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcurl=7.84.0=h91b91d3_0
  - libdap4=3.19.1=h6ec2957_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgdal=3.4.1=h05199a0_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libkml=1.3.0=h4fcabce_1010
  - liblief=0.11.5=h295c915_1
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h9e868ea_5
  - libnetcdf=4.8.1=h42ceab0_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libspatialite=4.3.0a=hbedb2dc_20
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzip=1.8.0=h5cef20c_0
  - libzopfli=1.0.3=he6710b0_0
  - llvmlite=0.38.0=py39h4ff587b_0
  - lxml=4.9.1=py39h1edc446_0
  - lz4=3.1.3=py39h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h7b6447c_2
  - markdown=3.3.4=py39h06a4308_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mock=4.0.3=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpi=1.0=mpich
  - mpich=3.3.2=external_0
  - mpmath=1.2.1=py39h06a4308_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - multipledispatch=0.6.0=py39h06a4308_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39h06a4308_1
  - navigator-updater=0.3.0=py39h06a4308_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.4.4=py39h06a4308_0
  - nbformat=5.5.0=py39h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py39h06a4308_0
  - nltk=3.7=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.4.12=py39h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numba=0.55.1=py39h51133e4_0
  - numexpr=2.8.3=py39h807cd23_0
  - numpydoc=1.4.0=py39h06a4308_0
  - olefile=0.46=pyhd3eb1b0_0
  - oniguruma=6.9.7.1=h27cfd23_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.0.10=py39h5eee18b_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.13.1=py39h06a4308_0
  - param=1.12.0=pyhd3eb1b0_0
  - parsel=1.6.0=py39h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - patch=2.7.6=h7b6447c_1001
  - patchelf=0.13=h295c915_0
  - pathlib=1.0.1=pyhd3eb1b0_1
  - pathspec=0.9.0=py39h06a4308_0
  - patsy=0.5.2=py39h06a4308_1
  - pcre=8.45=h295c915_0
  - pep8=1.7.1=py39h06a4308_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pixman=0.40.0=h36c2ea0_0
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - platformdirs=2.5.2=py39h06a4308_0
  - plotly=5.9.0=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - ply=3.11=py39h06a4308_0
  - poppler=0.81.0=h01f5e8b_2
  - poppler-data=0.4.11=hd8ed1ab_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - proj=6.2.1=hc80f0dc_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protego=0.1.16=py_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.11.5=py39h295c915_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py39h27cfd23_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.4.8=py39h06a4308_1
  - pycurl=7.45.1=py39h8f2d780_0
  - pydispatcher=2.0.5=py39h06a4308_2
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyerfa=2.0.0=py39h27cfd23_0
  - pyflakes=2.4.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyhamcrest=2.0.2=pyhd3eb1b0_2
  - pyjwt=2.4.0=py39h06a4308_0
  - pylint=2.14.5=py39h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyodbc=4.0.34=py39h6a678d5_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyqtwebengine=5.15.7=py39h6a678d5_1
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - pytables=3.6.1=py39h77479fe_1
  - pytest=7.1.2=py39h06a4308_0
  - python=3.9.13=haa1d7c7_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lsp-black=1.2.1=py39h06a4308_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.5.0=py39h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.0=py39h2531618_3
  - python_abi=3.9=2_cp39
  - pytz=2022.1=py39h06a4308_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywavelets=1.3.0=py39h7f8727e_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py39h7f8727e_1
  - pyzmq=23.2.0=py39h6a678d5_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.15.9=h06a4308_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.2=py39h06a4308_0
  - qtpy=2.2.0=py39h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - queuelib=1.5.0=py39h06a4308_0
  - readline=8.1.2=h7f8727e_1
  - regex=2022.7.9=py39h5eee18b_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - ripgrep=13.0.0=hbdeaff8_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py39h06a4308_1
  - ruamel.yaml=0.17.21=py39hb9d737c_1
  - ruamel.yaml.clib=0.2.6=py39h5eee18b_1
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - s3transfer=0.6.0=py39h06a4308_0
  - scikit-image=0.19.2=py39h51133e4_0
  - scikit-learn=1.0.2=py39h51133e4_1
  - scikit-learn-intelex=2021.6.0=py39h06a4308_0
  - scrapy=2.6.2=py39h06a4308_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - secretstorage=3.3.1=py39h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py39h06a4308_0
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py39h06a4308_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=5.0.2=py39h06a4308_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.3.3=py39h06a4308_0
  - spyder-kernels=2.3.3=py39h06a4308_0
  - sqlalchemy=1.4.39=py39h5eee18b_0
  - sqlite=3.39.3=h5082296_0
  - statsmodels=0.13.2=py39h7f8727e_0
  - sympy=1.10.1=py39h06a4308_0
  - tabulate=0.8.10=py39h06a4308_0
  - tbb=2021.6.0=hdb19cb5_0
  - tbb4py=2021.6.0=py39hdb19cb5_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py39h06a4308_1
  - terminado=0.13.1=py39h06a4308_0
  - testpath=0.6.0=py39h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tiledb=2.3.3=h1132f93_2
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.12=h1ccaba5_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - tomlkit=0.11.1=py39h06a4308_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py39h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - twisted=22.2.0=py39h5eee18b_1
  - typing-extensions=4.3.0=py39h06a4308_0
  - typing_extensions=4.3.0=py39h06a4308_0
  - tzdata=2022c=h04d1e81_0
  - ujson=5.4.0=py39h6a678d5_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - unixodbc=2.3.11=h5eee18b_0
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wget=1.21.3=h0b77cf5_0
  - whatthepatch=1.0.2=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - wrapt=1.14.1=py39h5eee18b_0
  - wurlitzer=3.0.2=py39h06a4308_0
  - xarray=0.20.1=pyhd3eb1b0_1
  - xerces-c=3.2.4=h94c2ce2_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.3=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zict=2.1.0=py39h06a4308_0
  - zipp=3.8.0=py39h06a4308_0
  - zlib=1.2.12=h5eee18b_3
  - zope=1.0=py39h06a4308_1
  - zope.interface=5.4.0=py39h7f8727e_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.3.0
      - affine==2.3.1
      - albumentations==1.0.3
      - astunparse==1.6.3
      - branca==0.4.2
      - build==0.9.0
      - bumpver==2022.1120
      - cachetools==5.2.0
      - certifi==2021.10.8
      - cffi==1.15.0
      - click==8.1.0
      - click-plugins==1.1.1
      - cligj==0.7.2
      - commonmark==0.9.1
      - cryptography==36.0.0
      - cytoolz==0.11.2
      - dask==2022.3.0
      - efficientnet==1.0.0
      - fiona==1.8.21
      - flatbuffers==1.12
      - folium==0.12.1.post1
      - fonttools==4.31.2
      - fsspec==2022.2.0
      - gast==0.4.0
      - gdal==3.3.2
      - geojson==2.5.0
      - geopandas==0.10.2
      - google-auth==2.15.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.1
      - h5py==3.6.0
      - image-classifiers==1.0.0
      - imagecodecs==2022.2.22
      - imageio==2.16.1
      - imgaug==0.4.0
      - jinja2==3.1.1
      - keras==2.9.0
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - lexid==2021.1006
      - libclang==14.0.6
      - locket==0.2.0
      - mapclassify==2.4.3
      - markupsafe==2.1.1
      - matplotlib==3.5.1
      - mercantile==1.2.1
      - munch==2.5.0
      - networkx==2.7.1
      - numpy==1.22.3
      - oauthlib==3.2.2
      - opencv-python==4.5.5.64
      - opencv-python-headless==4.6.0.66
      - opt-einsum==3.3.0
      - pandas==1.4.1
      - pathlib2==2.3.7.post1
      - pep517==0.13.0
      - pillow==9.0.1
      - pip==21.2.4
      - protobuf==3.19.6
      - pyopenssl==21.0.0
      - pyparsing==3.0.7
      - pyproj==3.3.0
      - ramp-fair==0.1.1
      - rasterio==1.2.10
      - readme-renderer==37.3
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - requests-toolbelt==0.10.1
      - rfc3986==2.0.0
      - rich==12.6.0
      - rsa==4.9
      - scikit-fmm==2022.8.15
      - scipy==1.8.0
      - segmentation-models==1.0.1
      - setuptools==58.0.4
      - shapely==1.8.0
      - snuggs==1.4.7
      - solaris==0.4.0
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.9.2
      - tensorflow-estimator==2.9.0
      - tensorflow-io-gcs-filesystem==0.28.0
      - termcolor==2.1.1
      - tf-estimator-nightly==2.8.0.dev2021122109
      - threadpoolctl==3.1.0
      - tifffile==2022.3.25
      - tinydb==4.7.0
      - tqdm==4.62.3
      - twine==4.0.2
      - unicodedata2==14.0.0
      - urllib3==1.26.7
      - xyzservices==2022.3.0