name: fAIr
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py38h080aedc_0
  - branca=0.5.0=pyhd8ed1ab_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.9.24=py38haa95532_0
  - cffi=1.15.1=py38h2bbff1b_0
  - cfitsio=3.470=h2bbff1b_7
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=py38haa95532_0
  - colorama=0.4.5=py38haa95532_0
  - cryptography=38.0.1=py38h21b164f_0
  - curl=7.85.0=h2bbff1b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.4.9=h6c2663c_0
  - fftw=3.3.9=h2bbff1b_1
  - fiona=1.8.13.post1=py38h758c064_0
  - folium=0.13.0=pyhd8ed1ab_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - freexl=1.0.6=h2bbff1b_0
  - gdal=3.0.2=py38hb978731_4
  - geopandas=0.12.1=pyhd8ed1ab_1
  - geopandas-base=0.12.1=pyha770c72_1
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.7.0=h4545760_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.6=h1756f20_1
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.4=py38haa95532_0
  - imagesize=1.4.1=py38haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jinja2=3.1.2=py38haa95532_0
  - joblib=1.1.1=py38haa95532_0
  - jpeg=9e=h2bbff1b_0
  - kealib=1.4.14=hde4a422_1
  - kiwisolver=1.4.2=py38hd77b12b_0
  - krb5=1.19.2=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcurl=7.85.0=h86230a5_0
  - libdeflate=1.8=h2bbff1b_5
  - libgdal=3.0.2=ha304284_4
  - libiconv=1.16=h2bbff1b_2
  - libnetcdf=4.8.1=h6685c40_1
  - libpng=1.6.37=h2a8f88b_0
  - libpq=12.9=hb652d5d_3
  - libspatialindex=1.9.3=h6c2663c_0
  - libspatialite=4.3.0a=h14feca5_20
  - libssh2=1.10.0=hcd4344a_0
  - libtiff=4.4.0=h8a3f274_1
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libzip=1.8.0=h49b8836_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - mapclassify=2.4.3=pyhd3eb1b0_0
  - markupsafe=2.1.1=py38h2bbff1b_0
  - matplotlib-base=3.5.3=py38hd77b12b_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - networkx=2.8.4=py38haa95532_0
  - numexpr=2.8.3=py38hb80d3ca_0
  - numpy=1.23.3=py38h3b20f71_0
  - numpy-base=1.23.3=py38h4da318b_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=1.1.1s=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.4=py38hd77b12b_0
  - pillow=9.2.0=py38hdc2b20a_1
  - pip=22.2.2=py38haa95532_0
  - proj=6.2.1=h3758d61_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38haa95532_0
  - pyproj=2.6.1.post1=py38h593ac45_1
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.13=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2022.1=py38haa95532_0
  - requests=2.28.1=py38haa95532_0
  - rtree=0.9.7=py38h2eaa2aa_1
  - scikit-learn=1.1.3=py38hd77b12b_0
  - scipy=1.9.3=py38he11b74f_0
  - setuptools=65.5.0=py38haa95532_0
  - shapely=1.8.4=py38h9064783_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sqlite=3.39.3=h2bbff1b_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tiledb=2.3.3=h3649cd2_2
  - tk=8.6.12=h2bbff1b_0
  - urllib3=1.26.12=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - xerces-c=3.2.3=ha925a31_0
  - xyzservices=2022.9.0=py38haa95532_0
  - xz=5.2.6=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - absl-py==1.3.0
    - affine==2.3.1
    - astunparse==1.6.3
    - cachetools==5.2.0
    - click==7.1.2
    - commonmark==0.9.1
    - docutils==0.17.1
    - flatbuffers==22.10.26
    - gast==0.4.0
    - geojson==2.5.0
    - google-auth==2.14.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.50.0
    - h5py==3.7.0
    - importlib-metadata==5.0.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - markdown==3.4.1
    - markdown-it-py==2.1.0
    - mdit-py-plugins==0.3.1
    - mdurl==0.1.2
    - mercantile==1.2.1
    - mypy-extensions==0.4.3
    - myst-parser==0.18.1
    - oauthlib==3.2.2
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - pathspec==0.10.1
    - platformdirs==2.5.2
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyogrio==0.4.2
    - pyyaml==6.0
    - rasterio==1.3.3
    - recommonmark==0.7.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - snuggs==1.4.7
    - sphinx-rtd-theme==1.1.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.1.0
    - tomli==2.0.1
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.10.0
